config/routes.rb
Rails.application.routes.draw do
  get 'session/login'
  post 'session/create'
  get 'session/logout'
  resources :users
  root 'index#input'
  get 'index/input'
  get 'index/output'
  get 'task/results'
  get 'session/results'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :password, confirmation: true, presence:true

    validates :username, presence:true, uniqueness: true, format: {with: /\A[a-zA-Z]+\z/, message: "only allows letters"}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionHelper

    before_action :require_login

    add_flash_types :danger, :info, :warning, :success
    
    private

    def require_login
        redirect_to session_login_url unless signed_in?
    end

end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def input
  end

  def output
    @n =params[:input].split.map{|x| Integer(x)}[0]
    del_sum_array = (1..@n).to_a.map do |x|
        del_sum = 0
        del = 1
        while del <= x and del*del<=x do
            if x % del == 0
                del_sum = del_sum + del
                if x/del != del 
                    del_sum += x/del
                end
            end
            del+=1
        end
        del_sum-x
    end
    @friendly_array = del_sum_array.select.with_index do |x,i|
        if x <= @n and x != i+1 and x>3 and i+1 == del_sum_array[x-1]
            [i+1,x]
        end
    end
    @friendly_array
  rescue StandardError
    @error= 'Некорректный ввод'
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :require_login, only: %i[login create]

  def login
  end

  def create
    user = User.find_by username: params[:username]
    if user&.authenticate(params[:password])
      sign_in user
      redirect_to root_url, success: "Вход осуществлен"
    else
      redirect_to session_login_url, danger: "Пользователь не зарегистрирован"
    end
  end

  def logout
    sign_out
    redirect_to session_login_url, info: "Вы вышли из системы"
  end

  def results
    @result = User.all
    render xml: @result
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  skip_before_action :require_login, only: %i[new create]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    respond_to do |format|
      if @user.save
        sign_in @user
        format.html { redirect_to @user }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:username, :password, :password_confirmation)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/session_helper.rb
module SessionHelper
    def sign_in(user)
        cookies.signed[:user_id] = { value: user.id, expires: 10.days, http_only: true}
        self.current_user = user
    end

    def signed_in?
        !current_user.nil?
    end

    def sign_out
        cookies.signed[:user_id] = nil
        self.current_user = nil
    end

    def current_user=(user)
        @current_user = user
    end

    def current_user
        @current_user ||= User.find_by(id: cookies.signed[:user_id])
    end
    
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/index/input.html.erb
<h1>Лабораторная работа №8</h1>
<p>Программа определяет дружественные числа,</p>
<p>лежащие в диапазоне от 1 до n</p>
<p><strong>Введите n</strong></p>
<form action = "/index/output/">
    <input name ="input">
    <input type = "submit" value="Отправить">
<form>
<br>
<%= link_to 'Выйти', session_logout_path %>

app/views/index/output.html.erb
<%if @error %>
    <p><%=@error%><p>
<%else%>
    <h1>Пары дружественных чисел в диапазоне от 1 до <%=@n%></h1>
    <table class="table">
            <tr>
                <td><strong>Число 1</strong></td>
                <td><strong>Число 2</strong></td>
            </tr>
            <% @friendly_array.each_with_index do |r,i|%>
                <% if i <=@friendly_array.length/2-1 %>
                <tr>
                    <td><%=@friendly_array[i*2]%></td>
                    <td><%=@friendly_array[i*2+1]%></td>
                </tr>
                <%end%>
            <%end%>
    </table>
<%end%>
<br>
<%= link_to 'Выйти', session_logout_path %>
<br>
<%= link_to 'Назад к вводу', index_input_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lb8App</title>
    <style type="text/css">
      div {
        width: 300px
      }
    </style>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= name %> scale'>
        <%= msg %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/session/login.html.erb
<%= flash[:notice] %>
<%= form_with url: session_create_url, method: :post, local:true do |f| %>
    <%= f.label :user_label, "Имя пользователя:"%>
    <%= f.text_field :username, required: true %>
    <%= f.label :password_label, "Пароль:"%>
    <%= f.password_field :password, required: true %><br><br>
    <%= f.submit :login, required: true %>
<% end %>
<br>
<%= link_to 'Регистрация', new_user_path%>

app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %>
    <%= form.text_field :username %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, required: true %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password digest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password_digest %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Создать нового пользователя', new_user_path %>
<br>
<%= link_to 'Перейти к вычислениям', index_input_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password digest:</strong>
  <%= @user.password_digest %>
</p>

<%= link_to 'Редактировать пользователя', edit_user_path(@user) %>
<br>
<%= link_to 'Посмотреть всех пользователей', users_path %>
<br>
<%= link_to 'Перейти к вычислениям', index_input_path %>